# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          #echo "PATH:"
          #echo "$PATH"|tr ':' '\n'
          #echo -e '\n/usr/bin:'
          #ls /usr/bin/
          #echo  -e '\n/usr/local/bin:'
          #ls /usr/local/bin
          #echo -e '\ntype python:'
          #type python
          #echo -e '\ntype python3:'
          #type python3
          #echo -e '\ntype pip3:'
          #type pip3
          
          #echo -e '\n/opt:'
          #ls /opt
          # python3 = python3.8.5
          # echo -e '\npython3 --version:'
          # python3 --version

          # find / -name python 2>/dev/null
          
          echo -e '\n/opt/hostedtoolcache/Python/3.9.5/x64/:'
          find /opt/hostedtoolcache/Python/3.9.5/x64/ -type d 

          echo -e '\n/opt/hostedtoolcache/Python/3.9.5/x64/bin:'
          ls /opt/hostedtoolcache/Python/3.9.5/x64/bin
          
